name: myapp
description: A exported flutter project from FUNCTION12


# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/page-1/images/bi-battery-full.png
    - assets/page-1/images/arcticons-rewards.png
    - assets/page-1/images/iconly-two-tone-home.png
    - assets/page-1/images/arrow-left.png
    - assets/page-1/images/bx-wifi.png
    - assets/page-1/images/arcticons-rewards-w4D.png
    - assets/page-1/images/iconly-two-tone-profile.png
    - assets/page-1/images/bx-signal-5.png
    - assets/page-1/images/bi-battery-full-p8Z.png
    - assets/page-1/images/.png
    - assets/page-1/images/-coT.png
    - assets/page-1/images/image-15.png
    - assets/page-1/images/-tDf.png
    - assets/page-1/images/bx-wifi-NKT.png
    - assets/page-1/images/bx-wifi-TLd.png
    - assets/page-1/images/iconly-two-tone-profile-gky.png
    - assets/page-1/images/-93F.png
    - assets/page-1/images/bi-battery-full-XbX.png
    - assets/page-1/images/-cgq.png
    - assets/page-1/images/ellipse-1.png
    - assets/page-1/images/-VgV.png
    - assets/page-1/images/-MbX.png
    - assets/page-1/images/arcticons-rewards-dFX.png
    - assets/page-1/images/-ohb.png
    - assets/page-1/images/-qRT.png
    - assets/page-1/images/-Ed7.png
    - assets/page-1/images/bx-signal-5-WK3.png
    - assets/page-1/images/forward.png
    - assets/page-1/images/bi-battery-full-pD7.png
    - assets/page-1/images/image-22.png
    - assets/page-1/images/icon-light-month-chevron.png
    - assets/page-1/images/bx-signal-5-wtV.png
    - assets/page-1/images/arrow-left-Umw.png
    - assets/page-1/images/bx-wifi-87j.png
    - assets/page-1/images/-U6M.png
    - assets/page-1/images/image-15-bg.png
    - assets/page-1/images/image-8.png
    - assets/page-1/images/image-12.png
    - assets/page-1/images/-PX7.png
    - assets/page-1/images/forward-sQu.png
    - assets/page-1/images/arrow-left-ayX.png
    - assets/page-1/images/-eSu.png
    - assets/page-1/images/-qFo.png
    - assets/page-1/images/-AZw.png
    - assets/page-1/images/-kpy.png
    - assets/page-1/images/bx-wifi-bDK.png
    - assets/page-1/images/image-15-bg-w1T.png
    - assets/page-1/images/bx-signal-5-Mgm.png
    - assets/page-1/images/image-16.png
    - assets/page-1/images/bx-wifi-6tR.png
    - assets/page-1/images/forward-H5j.png
    - assets/page-1/images/forward-Cjj.png
    - assets/page-1/images/-JL9.png
    - assets/page-1/images/-PJy.png
    - assets/page-1/images/-XRB.png
    - assets/page-1/images/arcticons-rewards-TAy.png
    - assets/page-1/images/-N6D.png
    - assets/page-1/images/image-15-H9B.png
    - assets/page-1/images/-h8u.png
    - assets/page-1/images/-UmF.png
    - assets/page-1/images/-Us3.png
    - assets/page-1/images/image-15-zNV.png
    - assets/page-1/images/forward-Vvh.png
    - assets/page-1/images/-7Lu.png
    - assets/page-1/images/-fdK.png
    - assets/page-1/images/forward-RsP.png
    - assets/page-1/images/-GhX.png
    - assets/page-1/images/arrow-left-jgD.png
    - assets/page-1/images/line-48.png
    - assets/page-1/images/image-15-bg-LJd.png
    - assets/page-1/images/-LCH.png
    - assets/page-1/images/-zM7.png
    - assets/page-1/images/auto-group-bepy.png
    - assets/page-1/images/bx-wifi-RuB.png
    - assets/page-1/images/image-21.png
    - assets/page-1/images/info.png
    - assets/page-1/images/arrow-left-4Gq.png
    - assets/page-1/images/image-3.png
    - assets/page-1/images/-jNy.png
    - assets/page-1/images/-Vsw.png
    - assets/page-1/images/-sVB.png
    - assets/page-1/images/image-19.png
    - assets/page-1/images/arrow-left-xp1.png
    - assets/page-1/images/image-15-dHB.png
    - assets/page-1/images/image-20.png
    - assets/page-1/images/-E2d.png
    - assets/page-1/images/-aMP.png
    - assets/page-1/images/-LbT.png
    - assets/page-1/images/group-10.png
    - assets/page-1/images/-JGh.png
    - assets/page-1/images/-JAD.png
    - assets/page-1/images/-ezm.png
    - assets/page-1/images/qrimg-1.png
    - assets/page-1/images/bx-signal-5-nLH.png
    - assets/page-1/images/forward-wiy.png
    - assets/page-1/images/-6VP.png
    - assets/page-1/images/-yAR.png
    - assets/page-1/images/wepik-export-20230707134426wsbx-1.png
    - assets/page-1/images/-cQy.png
    - assets/page-1/images/bx-wifi-kPs.png
    - assets/page-1/images/image-7.png
    - assets/page-1/images/qrimg-1-Dxu.png
    - assets/page-1/images/wepik-export-20230707134426wsbx-1-JNV.png
    - assets/page-1/images/rectangle-18819.png
    - assets/page-1/images/image-12-d7o.png
    - assets/page-1/images/group-10-XZj.png
    - assets/page-1/images/-do7.png
    - assets/page-1/images/external-link.png
    - assets/page-1/images/-h8m.png
    - assets/page-1/images/info-rYh.png
    - assets/page-1/images/external-link-SqP.png
    - assets/page-1/images/bi-battery-full-ZVb.png
    - assets/page-1/images/image-17.png
    - assets/page-1/images/bi-battery-full-Jws.png
    - assets/page-1/images/bx-wifi-n1o.png
    - assets/page-1/images/bx-signal-5-gos.png
    - assets/page-1/images/bi-battery-full-LFs.png
    - assets/page-1/images/bx-signal-5-5WH.png
    - assets/page-1/images/arrow-left-Hvy.png
    - assets/page-1/images/image-14.png
    - assets/page-1/images/bx-signal-5-BxD.png
    - assets/page-1/images/iconly-two-tone-home-maR.png
    - assets/page-1/images/subtract.png
    - assets/page-1/images/bx-signal-5-CND.png
    - assets/page-1/images/menu.png
    - assets/page-1/images/subtract-kL9.png
    - assets/page-1/images/arrow-left-XLd.png
    - assets/page-1/images/arrow-left-oM3.png
    - assets/page-1/images/bx-signal-5-1PX.png
    - assets/page-1/images/bx-wifi-Axq.png
    - assets/page-1/images/bx-signal-5-Dpd.png
    - assets/page-1/images/-HCD.png
    - assets/page-1/images/iconly-two-tone-home-6Yy.png
    - assets/page-1/images/-Trh.png
    - assets/page-1/images/iconly-two-tone-home-vDo.png
    - assets/page-1/images/arcticons-rewards-ywP.png
    - assets/page-1/images/image-2.png
    - assets/page-1/images/arrow-left-W1P.png
    - assets/page-1/images/bx-signal-5-jeq.png
    - assets/page-1/images/bi-battery-full-tXj.png
    - assets/page-1/images/iconly-two-tone-home-e17.png
    - assets/page-1/images/bi-battery-full-X5B.png
    - assets/page-1/images/subtract-zUZ.png
    - assets/page-1/images/bx-signal-5-7Q5.png
    - assets/page-1/images/bi-battery-full-XTo.png
    - assets/page-1/images/menu-JDf.png
    - assets/page-1/images/iconly-two-tone-profile-qYM.png
    - assets/page-1/images/arrow-left-1Fo.png
    - assets/page-1/images/subtract-D2R.png
    - assets/page-1/images/bx-signal-5-2eV.png
    - assets/page-1/images/arrow-left-PWy.png
    - assets/page-1/images/subtract-uSh.png
    - assets/page-1/images/subtract-cVX.png
    - assets/page-1/images/subtract-JnD.png
    - assets/page-1/images/-k3B.png
    - assets/page-1/images/bx-wifi-T7F.png
    - assets/page-1/images/bi-battery-full-ArD.png
    - assets/page-1/images/whatsapp-image-2023-07-07-at-540-1.png
    - assets/page-1/images/subtract-g57.png
    - assets/page-1/images/iconly-two-tone-profile-bSy.png
    - assets/page-1/images/menu-vss.png
    - assets/page-1/images/bi-battery-full-vwj.png
    - assets/page-1/images/bi-battery-full-cmw.png
    - assets/page-1/images/image-18.png
    - assets/page-1/images/line-48-UH7.png
    - assets/page-1/images/iconly-two-tone-profile-iW5.png
    - assets/page-1/images/iconly-two-tone-home-pxy.png
    - assets/page-1/images/bi-battery-full-iCh.png
    - assets/page-1/images/bx-wifi-6yw.png
    - assets/page-1/images/bx-signal-5-eLh.png
    - assets/page-1/images/image-4.png
    - assets/page-1/images/-iUH.png
    - assets/page-1/images/-c6M.png
    - assets/page-1/images/image-6.png
    - assets/page-1/images/image-2-X8d.png
    - assets/page-1/images/image-11.png
    - assets/page-1/images/image-12-x4H.png
    - assets/page-1/images/image-14-RgV.png
    - assets/page-1/images/arrow-left-mDT.png
    - assets/page-1/images/subtract-rHP.png
    - assets/page-1/images/bi-battery-full-9mK.png
    - assets/page-1/images/bx-wifi-GqP.png
    - assets/page-1/images/bx-wifi-u6h.png
    - assets/page-1/images/bi-battery-full-T4m.png
    - assets/page-1/images/iconly-two-tone-profile-y4u.png
    - assets/page-1/images/bx-wifi-N1f.png
    - assets/page-1/images/bx-signal-5-2PT.png
    - assets/page-1/images/image-13.png
    - assets/page-1/images/arrow-left-kpy.png
    - assets/page-1/images/image-5.png
    - assets/page-1/images/bx-wifi-1Fw.png
    - assets/page-1/images/subtract-thF.png
    - assets/page-1/images/arcticons-rewards-13w.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
